root: true
env:
  node: true
extends:
  - 'plugin:vue/essential'
  - '@vue/standard'
  - '@vue/typescript'
rules:
  no-console: 'off'
  no-debugger: 'off'
parserOptions:
  parse: babel-eslint
  parser: '@typescript-eslint/parser'
